### ISSUE TITLE
As a user who is unfamiliar with Azul, I want to learn how to play the game

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#108]
- [x] sopra-fs22-group-34/client#47
- [x] sopra-fs22-group-34/client#48
- [x] sopra-fs22-group-34/client#49
- [x] sopra-fs22-group-34/client#50
- [x] sopra-fs22-group-34/client#65
