### ISSUE TITLE
As a player, I want the end game stage to calculate my points correctly

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#11]
- [x] #107
- [x] sopra-fs22-group-34/server#61
- [x] sopra-fs22-group-34/server#62
- [x] sopra-fs22-group-34/server#63
- [x] sopra-fs22-group-34/server#64
- [x] sopra-fs22-group-34/server#65
- [x] sopra-fs22-group-34/server#66
- [x] sopra-fs22-group-34/client#43
- [x] sopra-fs22-group-34/client#44
- [x] #105
