### ISSUE TITLE
As a player, I want to be able to leave a game if I'm no longer having fun or run out of time

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#119]
- [x] sopra-fs22-group-34/server#120
- [x] sopra-fs22-group-34/client#59
- [x] sopra-fs22-group-34/client#60
- [x] sopra-fs22-group-34/client#61
- [x] sopra-fs22-group-34/server#124

**Comment by noraberinger** [comment]
All tasks completed during Week 8
