### ISSUE TITLE
As a user, I want to have a player score to show off how good I am at the game

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#12]
- [x] sopra-fs22-group-34/server#96
- [x] sopra-fs22-group-34/server#97
- [x] sopra-fs22-group-34/server#98
- [x] sopra-fs22-group-34/server#99
- [x] sopra-fs22-group-34/client#41
- [x] sopra-fs22-group-34/server#102
