### ISSUE TITLE
As a user, I want to be able to spectate other people's games so I can learn from them

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#13]
- [x] sopra-fs22-group-34/server#113
- [x] sopra-fs22-group-34/client#51
- [x] sopra-fs22-group-34/client#52
- [x] sopra-fs22-group-34/client#53
- [x] sopra-fs22-group-34/server#117
- [x] sopra-fs22-group-34/client#54
