### ISSUE TITLE
As a player, I want each turn to have a fixed time limit so I don't have to wait too long

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#15]
- [x] sopra-fs22-group-34/server#93
- [x] #134
- [x] sopra-fs22-group-34/server#133
- [x] sopra-fs22-group-34/client#38
- [x] sopra-fs22-group-34/client#39
- [x] sopra-fs22-group-34/client#40
- [x] #142
- [ ] sopra-fs22-group-34/server#125
- [ ] sopra-fs22-group-34/server#126
- [x] https://github.com/sopra-fs22-group-34/client/issues/70

**Comment by noraberinger** [comment]
Task #125 and #126 left for implementation in the future otherwise closed
