### ISSUE TITLE
As a user, I want to be able to create a new game so other players can join me

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#4]
- [x] sopra-fs22-group-34/client#7
- [x] sopra-fs22-group-34/client#20
- [x] sopra-fs22-group-34/client#22
- [x] sopra-fs22-group-34/server#27
- [x] sopra-fs22-group-34/client#8
- [x] sopra-fs22-group-34/client#21
- [x] sopra-fs22-group-34/client#23
- [x] sopra-fs22-group-34/client#24
- [x] sopra-fs22-group-34/server#86
- [x] #89
