### ISSUE TITLE
As a user, I want to be able to play the game with my friends since I like them more than random strangers on the internet

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#5]
- [x] sopra-fs22-group-34/server#30
- [x] sopra-fs22-group-34/client#68
- [x] #138
- [x] sopra-fs22-group-34/client#10
- [x] sopra-fs22-group-34/client#9
