### ISSUE TITLE
As a user, I want there to be a consistent turn order so the game remains fair

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#6]
- [x] #137
- [x] sopra-fs22-group-34/server#34
- [x] sopra-fs22-group-34/server#35
- [x] #127
- [x] sopra-fs22-group-34/client#11
- [x] sopra-fs22-group-34/client#12
