### ISSUE TITLE
As a player, if it is my turn, I want to click on a tile and transfer it to a pattern line in order to make a strategic move

### ISSUE THREAD

**Issue by egohlin** [sopra-fs22-group-34/server#8]
- [x] sopra-fs22-group-34/client#14
- [x] sopra-fs22-group-34/client#15
- [x] sopra-fs22-group-34/client#13
- [x] sopra-fs22-group-34/server#47
- [x] sopra-fs22-group-34/server#48
- [x] sopra-fs22-group-34/server#49
- [x] sopra-fs22-group-34/server#50
